In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
data=pd.read_csv('future3yue.csv')

In [2]:
data

          数据时间
0     2021/9/1
1     2021/9/2
2     2021/9/3
3     2021/9/4
4     2021/9/5
..         ...
86  2021/11/26
87  2021/11/27
88  2021/11/28
89  2021/11/29
90  2021/11/30

[91 rows x 1 columns]

In [3]:
data['数据时间'] = pd.to_datetime(data['数据时间'])
data['月'] = data['数据时间'].dt.month 
data['天'] = data['数据时间'].dt.day
data['小时'] = data['数据时间'].dt.hour
data['一年第几天'] = data['数据时间'].dt.dayofyear
data['一年第几周'] = data['数据时间'].dt.isocalendar().week
data['weekday'] = data['数据时间'].dt.weekday

In [4]:
period_dict ={
            23: '深夜', 0: '深夜', 1: '深夜',
            2: '凌晨', 3: '凌晨', 4: '凌晨',
            5: '早晨', 6: '早晨', 7: '早晨',
            8: '上午', 9: '上午', 10: '上午', 11: '上午',
            12: '中午', 13: '中午',
            14: '下午', 15: '下午', 16: '下午', 17: '下午',
            18: '傍晚',
            19: '晚上', 20: '晚上', 21: '晚上', 22: '晚上',
            }
data['时间段']=data['小时'].map(period_dict)
dict1 = {'深夜':1, '凌晨':2, '早晨':3, '上午':4, '中午':5, '下午':6, '傍晚':7, '晚上':8}
data['时间段'] = data['时间段'].map(dict1)

In [5]:
season_dict = {
                1: '春季', 2: '春季', 3: '春季',
                4: '夏季', 5: '夏季', 6: '夏季',
                7: '秋季', 8: '秋季', 9: '秋季',
                10: '冬季', 11: '冬季', 12: '冬季',
            }
data['季节']=data['月'].map(season_dict)
dict = {'春季':1,'夏季':2,'秋季':3,'冬季':4}
data['季节'] = data['季节'].map(dict)

In [6]:
data['是否月初'] = data['数据时间'].apply(lambda x: x.is_month_start)
# 是否月末
data['是否月末'] = data['数据时间'].apply(lambda x: x.is_month_end)
# 是否季节初
data['是否季节初'] = data['数据时间'].apply(lambda x: x.is_quarter_start)
# 是否季节末
data['是否季节末'] = data['数据时间'].apply(lambda x: x.is_quarter_end)
data['是否周末'] = data['数据时间'].apply(lambda x: True if x.dayofweek in [5, 6] else False)

In [7]:
data['是否月末'] = [int(i) for i in data['是否月末']]
data['是否季节初'] = [int(i) for i in data['是否季节初']]
data['是否季节末'] = [int(i) for i in data['是否季节末']]
data['是否周末'] = [int(i) for i in data['是否周末']]
data['是否月初'] = [int(i) for i in data['是否月初']]

In [8]:
data

,数据时间,月,天,小时,一年第几天,一年第几周,weekday,时间段,季节,是否月初,是否月末,是否季节初,是否季节末,是否周末
0,2021-09-01,9,1,0,244,35,2,1,3,1,0,0,0,0
1,2021-09-02,9,2,0,245,35,3,1,3,0,0,0,0,0
2,2021-09-03,9,3,0,246,35,4,1,3,0,0,0,0,0
3,2021-09-04,9,4,0,247,35,5,1,3,0,0,0,0,1
4,2021-09-05,9,5,0,248,35,6,1,3,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
86,2021-11-26,11,26,0,330,47,4,1,4,0,0,0,0,0
87,2021-11-27,11,27,0,331,47,5,1,4,0,0,0,0,1
88,2021-11-28,11,28,0,332,47,6,1,4,0,0,0,0,1
89,2021-11-29,11,29,0,333,48,0,1,4,0,0,0,0,0
90,2021-11-30,11,30,0,334,48,1,1,4,0,1,0,0,0

In [10]:
#输出数据
column=['数据时间','月', '天', '小时', '一年第几天', '一年第几周', 'weekday',\
                     '时间段', '季节', '是否月初','是否月末', '是否季节初', '是否季节末', '是否周末']
future3yue_new=pd.DataFrame(columns=column,data=data)
future3yue_new.to_csv('future3yue_new.csv')

0         0
1         0
2         0
3         0
4         0
         ..
128539    1
128540    1
128541    1
128542    1
128543    1
Name: weekday, Length: 128544, dtype: int64